export { default as Home } from './Home'
export { default as IndividuosSrv } from './Servicios/Servicios.js'
export { default as EmpresasSrv } from './empresas/Empresas.js'
export { default as EComerceSrv } from './EComerce/EComerce.js'

export { default as Nosotros } from './Nosotros/Nosotros'
export { default as Seguimiento } from './Tracking/Tracking.js'
export { default as Cotiza } from './Cotiza/Cotiza.js'
export { default as GeneraEnvio } from './GeneraEnvio/Genera.js'
export { default as Contacto } from './Contacto/Contacto.js'
export { default as Tracking } from './Tracking/Tracking.js'
export { default as BlogTips } from './Blog/Bolg.js'
// pagina anteriores
export { default as Individuos } from './Individuos'
export { default as Landing_2 } from './Landing_2'
export { default as Empresas } from './Empresas'
export { default as LandingEmpresa2 } from './Landing_empresa_2'
export { default as ThankYouPage } from './ThankYouPage'
